version: '3'

services:
  web:
    build: .
    ports:
      - "80:8000"
    restart: always
    # env_file: ./server/.env # TODO - uncomment this to auto-load your .env file!
    environment:
      NODE_ENV: production
      PORT: 8000
    networks:
      - outside
      - internal
    
  # // docker run --rm -it -v ${PWD}:/build --workdir /build cirrusci/flutter:stable flutter test
  flutter:
    image: cirrusci/flutter:stable
    restart: always
    command: flutter test
    environment:
      NODE_ENV: production
    networks:
      - outside
      - internal

#logging:
#  driver: syslog
#  options:
#    syslog-address: "tcp://192.168.0.42:123"